### ISSUE TITLE
Improve output generation

### ISSUE THREAD

**Issue by KasperBahrentzAAU** [blitzher/P4-lang#46]
**To-do:**

_Toggles:_
- [x] Description should have a toggle
- [x] Sections should be collapsible by pressing a dedicated button

_Sub-instructions:_
- [x] Add output/yield to instructions
- [x] Kitchenware should be included in instructions
- [x] Ingredients should have units in instructions
- [x] Ingredients and kitchenware should be comma separated in instructions
- [x] Ingredients and kitchenware should have a header in the instructions

_General layout:_
- [x] Make header
- [x] Make columns
- [x] Add field headers

_Fields:_
- [x] Add nutrients
- [x] Add servings
- [x] Add the other time headers

_Ingredients and kitchenware:_
- [x] Add amounts to ingredients in the ingredient list
- [x] Ingredients should be something-separated
- [x] Kitchenware should be something-separated 
- [x] Tags, ingredients, kitchenware and such should be presented in a list
- [x] Optional ingredients should be written in seperate header

![Carbonara_Mockup](https://user-images.githubusercontent.com/74188293/163172089-a012e6aa-13cf-4073-874d-4e97ffe35229.png)
